### ISSUE TITLE
Channel location file

### ISSUE THREAD

**Issue by arnodelorme** [arnodelorme/bva-io#4]
See attached file. The code snippet below allow to read electrodes

xDoc = xmlread('elettrodi_benedetta.bvef');
allListItems = xDoc.getElementsByTagName('Electrode')
allListItems.getLength

See the function xmlread for how to decode the rest of the file, and write an importer compatible with EEG.chanlocs

**Comment by arnodelorme** [comment]
[elettrodi_benedetta.bvef.zip](https://github.com/widmann/bva-io/files/3879724/elettrodi_benedetta.bvef.zip)

**Comment by widmann** [comment]
We have an importer (loadbvef.m) already?!

**Comment by arnodelorme** [comment]
Ah OK, was not aware of that (or forgot). Closing the report then. Thank you Andreas.
